#reglage serveur
server :
  port: 10000

#nom appli
spring :
  application :
    name : ploufMembres
  #acces BD
  data:
    mongodb:
      database: dbmembres
      host: 192.168.56.50
      port: 27017
      username: root
      password: passroot
